
services:
  postgresql:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_PROXY=edge
      - KC_HOSTNAME=localhost
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak-spi/build/libs/keycloak-leal-spi-0.0.1-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-leal-spi.jar
    command: ["start-dev"]


#add postgres on keycloak