spring:
  application:
    name: spring_auth_keycloak
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/test
          jwk-set-uri: http://localhost:8180/realms/test/protocol/openid-connect/certs
          # Configuração para aceitar tokens JWT emitidos pelo SPI
          audience: account